logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: nikhil
    password: nikhil
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    default-property-inclusion: non_absent
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
      enabled: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/webauthn
webauthn:
  relying-party-id: localhost
  relying-party-name: Example Application
  relying-party-icon: http://localhost:8080/assets/logo.png
  relying-party-origins: http://localhost:8080
  endpoints:
    registrationStartPath: /api/registration/start
    registrationAddPath: /api/registration/add
    registrationFinishPath: /api/registration/finish
    assertionStartPath: /api/assertion/start
    assertionFinishPath: /api/assertion/finish
